Continued.

diff --git a/ifdown b/ifdown
--- a/ifdown
+++ b/ifdown
@@ -1,4 +1,4 @@
-#!/bin/bash 
+#!/bin/sh 
 ########################################################################
 # Begin /sbin/ifdown
 #
@@ -25,10 +25,10 @@ while [ $# -gt 0 ]; do
    case "$1" in
       --help | -h)     help="y"; break ;;
 
-      --version | -V)  echo "${VERSTR}"; exit 0 ;;
+      --version | -V)  echo "$VERSTR"; exit 0 ;;
 
-      -*)              echo "ifup: ${1}: invalid option" >&2
-                       echo "${USAGE}" >& 2
+      -*)              echo "ifup: $1: invalid option" >&2
+                       echo "$USAGE" >& 2
                        exit 2 ;;
                     
       *)               break ;;
@@ -68,11 +68,11 @@ if [ "$IFACE" = "" ]; then
 fi
 
 # We only need to first service to bring down the interface
-S=`echo ${SERVICE} | cut -f1 -d" "`
+S=$(echo "$SERVICE" | cut -f1 -d" ")
 
-if ip link show ${IFACE} > /dev/null 2>&1; then
-   if [ -n "${S}" -a -x "/lib/services/${S}" ]; then
-     IFCONFIG=${file} /lib/services/${S} ${IFACE} down
+if ip link show "$IFACE" > /dev/null 2>&1; then
+   if [ -n "$S" ] && [ -x "/lib/services/$S" ]; then
+     IFCONFIG=${file} "/lib/services/$S" "$IFACE" down
    else
      MSG="Unable to process ${file}.  Either "
      MSG="${MSG}the SERVICE variable was not set "
@@ -81,20 +81,19 @@ if ip link show ${IFACE} > /dev/null 2>&1; then
      exit 1
   fi
 else
-   log_warning_msg "Interface ${1} doesn't exist."
+   log_warning_msg "Interface $1 doesn't exist."
 fi
 
 # Leave the interface up if there are additional interfaces in the device
-link_status=`ip link show ${IFACE} 2>/dev/null`
+link_status=$(ip link show "$IFACE" 2>/dev/null)
 
-if [ -n "${link_status}" ]; then
-   if [ "$(echo "${link_status}" | grep UP)" != "" ]; then
-      if [ "$(ip addr show ${IFACE} | grep 'inet ')" == ""  ]; then
-         log_info_msg "Bringing down the ${IFACE} interface..."
-         ip link set ${IFACE} down
+[ -n "$link_status" ] &&
+    echo "$link_status" | grep -q UP &&
+    ! ip addr show "$IFACE" | grep -q'inet ' && {
+         log_info_msg "Bringing down the $IFACE interface..."
+         ip link set "$IFACE" down
          evaluate_retval
-      fi
-   fi
-fi
+    }
+
 
 # End /sbin/ifdown
diff --git a/ifup b/ifup
--- a/ifup
+++ b/ifup
@@ -8,6 +8,8 @@
 #               Kevin P. Fleming - kpfleming@linuxfromscratch.org
 # Update      : Bruce Dubbs - bdubbs@linuxfromscratch.org
 #               DJ Lucas - dj@linuxfromscratch.org
+# 
+# Modified    : yul3n for kara linux
 #
 # Version     : LFS 7.7
 #
@@ -17,16 +19,24 @@
 #
 ########################################################################
 
-up()
-{
-  log_info_msg "Bringing up the ${1} interface..."
+isdigit() {
+    case $1 in
+	^[0-9]+$) return 1
+		  ;;
+	*) return 0
+	   ;;
+    esac
+}
 
-  if ip link show $1 > /dev/null 2>&1; then
-     link_status=`ip link show $1`
+up() {
+  log_info_msg "Bringing up the $1 interface..."
 
-     if [ -n "${link_status}" ]; then
-        if ! echo "${link_status}" | grep -q UP; then
-           ip link set $1 up
+  if ip link show "$1" > /dev/null 2>&1; then
+     link_status=$(ip link show "$1")
+
+     if [ -n "$link_status" ]; then
+        if ! echo "$link_status" | grep -q UP; then
+           ip link set "$1" up
         fi
      fi
 
@@ -41,25 +51,25 @@ up()
 RELEASE="7.7"
 
 USAGE="Usage: $0 [ -hV ] [--help] [--version] interface"
-VERSTR="LFS ifup, version ${RELEASE}"
+VERSTR="LFS ifup, version $RELEASE"
 
 while [ $# -gt 0 ]; do
    case "$1" in
       --help | -h)     help="y"; break ;;
 
-      --version | -V)  echo "${VERSTR}"; exit 0 ;;
+      --version | -V)  echo "$VERSTR"; exit 0 ;;
    
-      -*)              echo "ifup: ${1}: invalid option" >&2
-                       echo "${USAGE}" >& 2
+      -*)              echo "ifup: $1: invalid option" >&2
+                       echo "$USAGE" >& 2
                        exit 2 ;;
                        
       *)               break ;;
    esac
 done
 
-if [ -n "$help" ]; then
-   echo "${VERSTR}"
-   echo "${USAGE}"
+[ -n "$help" ] && {
+   echo "$VERSTR"
+   echo "$USAGE"
    echo
    cat << HERE_EOF
 ifup is used to bring up a network interface.  The interface
@@ -68,83 +78,78 @@ interface specifications file, e.g. /etc/sysconfig/ifconfig.eth0:2.
 
 HERE_EOF
    exit 0
-fi
+}
 
-file=/etc/sysconfig/ifconfig.${1}
+file=/etc/sysconfig/ifconfig."$1"
 
 # Skip backup files
-[ "${file}" = "${file%""~""}" ] || exit 0
+[ "$file" = "${file%""~""}" ] || exit 0
 
 . /lib/lsb/init-functions
 
-if [ ! -r "${file}" ]; then
-   log_failure_msg "Unable to bring up ${1} interface! ${file} is missing or cannot be accessed."
+[ ! -r "$file" ] && {
+   log_failure_msg "Unable to bring up $1 interface! $file is missing or cannot be accessed."
    exit 1
-fi
+}
 
-.  $file
+#shellcheck disable=SC1090
+.  "$file"
 
-if [ "$IFACE" = "" ]; then
+[ "$IFACE" = "" ] && {
    log_failure_msg "Unable to bring up ${1} interface! ${file} does not define an interface [IFACE]."
    exit 1
-fi
+}
 
 # Do not process this service if started by boot, and ONBOOT
 # is not set to yes
-if [ "${IN_BOOT}" = "1" -a "${ONBOOT}" != "yes" ]; then
-   exit 0
-fi
+[ "${IN_BOOT}" = "1" ] && [ "${ONBOOT}" != "yes" ] && exit 0
 
 # Bring up the interface
-if [ "$VIRTINT" != "yes" ]; then
-   up ${IFACE}
-fi
+[ "$VIRTINT" != "yes" ] && up "$IFACE"
 
 for S in ${SERVICE}; do
-  if [ ! -x "/lib/services/${S}" ]; then
-    MSG="\nUnable to process ${file}.  Either " 
-    MSG="${MSG}the SERVICE '${S} was not present "
+  if [ ! -x "/lib/services/$S" ]; then
+    MSG="\nUnable to process $file.  Either " 
+    MSG="${MSG}the SERVICE '$S was not present "
     MSG="${MSG}or cannot be executed."
     log_failure_msg "$MSG"
     exit 1
   fi
 done
 
-if [ "${SERVICE}" = "wpa" ]; then log_success_msg; fi
+[ "$SERVICE" = "wpa" ] && log_success_msg
 
 # Create/configure the interface
 for S in ${SERVICE}; do 
-  IFCONFIG=${file} /lib/services/${S} ${IFACE} up
+  IFCONFIG=$file "/lib/services/$S" "$IFACE" up
 done
 
 # Set link up virtual interfaces
-if [ "${VIRTINT}" == "yes" ]; then
-   up ${IFACE}
-fi
+[ "$VIRTINT" = "yes" ] && up "$IFACE"
 
 # Bring up any additional interface components
-for I in $INTERFACE_COMPONENTS; do up $I; done
+for I in $INTERFACE_COMPONENTS; do up "$I"; done
 
 # Set MTU if requested. Check if MTU has a "good" value.
-if test -n "${MTU}"; then
-   if [[ ${MTU} =~ ^[0-9]+$ ]] && [[ $MTU -ge 68 ]] ; then
+[ -n "$MTU" ] && {
+    if isdigit 1 && [ "$MTU" -ge 68 ] ; then
       for I in $IFACE $INTERFACE_COMPONENTS; do 
-         ip link set dev $I mtu $MTU; 
+         ip link set dev "$I" mtu "$MTU"; 
       done
    else
       log_info_msg2 "Invalid MTU $MTU"
    fi
-fi 
+}
 
 # Set the route default gateway if requested
-if [ -n "${GATEWAY}" ]; then
+[ -n "$GATEWAY" ] && {
    if ip route | grep -q default; then
       log_warning_msg "Gateway already setup; skipping."
    else
       log_info_msg "Adding default gateway ${GATEWAY} to the ${IFACE} interface..."
-      ip route add default via ${GATEWAY} dev ${IFACE}
+      ip route add default via "$GATEWAY" dev "$IFACE"
       evaluate_retval
    fi
-fi
+}
 
 # End /sbin/ifup
